# -*- coding: utf-8 -*-
"""Resume Scanner.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1O7k0x4yzuphreiz7pBgc5cSzGIvV1obz
"""

# description: create a program to see how similar a resume is to a job description

# install the docx2txt package to take a word document and convert it to txt
!pip install docx2txt

# import the library
import docx2txt

# load the data
from google.colab import files
uploaded = files.upload()

# store the resume in a variable
resume = docx2txt.process("resume.docx")

# print the resume
print(resume)

# store the job description into a variable
jobDescription = docx2txt.process("Role Description.docx")

# print the job description
print(jobDescription)

# create a list of text
text=[resume, jobDescription]

# creat a count vector object to count each word in the text
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
count_matrix =cv.fit_transform(text)

# import sklearn to use the cosine similarity function
from sklearn.metrics.pairwise import cosine_similarity

# print the similarity scores
print("\nSimilarity score:")
print(cosine_similarity(count_matrix))

# get the match percentage
matchPercentage = cosine_similarity(count_matrix)[0][1]*100
matchPercentage = round(matchPercentage, 2) # round to 2 decimal places
print("your resume matches about " + str(matchPercentage) + " % of the job description.")